version: '3.7'
services:
    mgmt:
        build: 
            context: archappl
        env_file: .env
        environment:
            - COMPONENT=mgmt
        restart: unless-stopped
        depends_on: 
            - config_db
        network_mode: host
        volumes: 
            - ./archappl/webapps/mgmt:/usr/local/tomcat/webapps
            - ./archappl/conf:/usr/local/tomcat/archappl_conf
            - ${STS_PATH}:/usr/local/tomcat/storage/sts
            - ${MTS_PATH}:/usr/local/tomcat/storage/mts
            - ${LTS_PATH}:/usr/local/tomcat/storage/lts
    engine:
        build: 
            context: archappl
        env_file: .env
        environment:
            - COMPONENT=engine
        restart: unless-stopped
        depends_on: 
            - config_db
        network_mode: host
        volumes: 
            - ./archappl/webapps/engine:/usr/local/tomcat/webapps
            - ./archappl/conf:/usr/local/tomcat/archappl_conf
            - ${STS_PATH}:/usr/local/tomcat/storage/sts
            - ${MTS_PATH}:/usr/local/tomcat/storage/mts
            - ${LTS_PATH}:/usr/local/tomcat/storage/lts
    etl:
        build: 
            context: archappl
        env_file: .env
        environment:
            - COMPONENT=etl
        restart: unless-stopped
        depends_on: 
            - config_db
        network_mode: host
        volumes: 
            - ./archappl/webapps/etl:/usr/local/tomcat/webapps
            - ./archappl/conf:/usr/local/tomcat/archappl_conf
            - ${STS_PATH}:/usr/local/tomcat/storage/sts
            - ${MTS_PATH}:/usr/local/tomcat/storage/mts
            - ${LTS_PATH}:/usr/local/tomcat/storage/lts
    retrieval:
        build: 
            context: archappl
        env_file: .env
        environment:
            - COMPONENT=retrieval
        restart: unless-stopped
        depends_on: 
            - config_db
        network_mode: host
        volumes: 
            - ./archappl/webapps/retrieval:/usr/local/tomcat/webapps
            - ./archappl/conf:/usr/local/tomcat/archappl_conf
            - ${STS_PATH}:/usr/local/tomcat/storage/sts
            - ${MTS_PATH}:/usr/local/tomcat/storage/mts
            - ${LTS_PATH}:/usr/local/tomcat/storage/lts
    config_db:
        build: config_db
        env_file: .env
        restart: unless-stopped
        volumes:
            - ${CONFIG_DB_PATH}:/var/lib/mysql
        network_mode: host